//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzickiFestivali.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuzickiFestivali.API.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno ste potvrdili svoj dolazak!.
        /// </summary>
        public static string Appearance_ArrivalConfirmed {
            get {
                return ResourceManager.GetString("Appearance_ArrivalConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomena ne može biti duža od 500 karaktera..
        /// </summary>
        public static string Appearance_NoteMaxLength {
            get {
                return ResourceManager.GetString("Appearance_NoteMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapis o nastupanju nije pronađen..
        /// </summary>
        public static string Appearance_NotFound {
            get {
                return ResourceManager.GetString("Appearance_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvođač ili vremenski termin nisu pronađeni..
        /// </summary>
        public static string Appearance_PerformerOrSlotNotFound {
            get {
                return ResourceManager.GetString("Appearance_PerformerOrSlotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga ne može biti duža od 100 karaktera..
        /// </summary>
        public static string Appearance_RoleMaxLength {
            get {
                return ResourceManager.GetString("Appearance_RoleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga izvođača je obavezna..
        /// </summary>
        public static string Appearance_RoleRequired {
            get {
                return ResourceManager.GetString("Appearance_RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvođač je uspešno raspoređen u termin. Status dolaska je postavljen na &apos;Nepotvrđen&apos;..
        /// </summary>
        public static string Appearance_SuccessAssignment {
            get {
                return ResourceManager.GetString("Appearance_SuccessAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvođač je uspešno uklonjen iz termina..
        /// </summary>
        public static string Appearance_SuccessRemoval {
            get {
                return ResourceManager.GetString("Appearance_SuccessRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija zaposlenog je obavezna..
        /// </summary>
        public static string Employee_PositionRequired {
            get {
                return ResourceManager.GetString("Employee_PositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacitet festivala mora biti između 1 i 1.000.000 posetilaca..
        /// </summary>
        public static string Festival_CapacityRange {
            get {
                return ResourceManager.GetString("Festival_CapacityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis festivala je obavezan..
        /// </summary>
        public static string Festival_DescriptionRequired {
            get {
                return ResourceManager.GetString("Festival_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum završetka festivala je obavezan..
        /// </summary>
        public static string Festival_EndDateRequired {
            get {
                return ResourceManager.GetString("Festival_EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv festivala ne može biti duži od 100 karaktera..
        /// </summary>
        public static string Festival_NameMaxLength {
            get {
                return ResourceManager.GetString("Festival_NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv festivala je obavezan..
        /// </summary>
        public static string Festival_NameRequired {
            get {
                return ResourceManager.GetString("Festival_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival sa zadatim identifikatorom nije pronađen..
        /// </summary>
        public static string Festival_NotFound {
            get {
                return ResourceManager.GetString("Festival_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum početka festivala je obavezan..
        /// </summary>
        public static string Festival_StartDateRequired {
            get {
                return ResourceManager.GetString("Festival_StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival je uspešno obrisan..
        /// </summary>
        public static string Festival_SuccessDelete {
            get {
                return ResourceManager.GetString("Festival_SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lajk za ovaj nastup nije pronađen..
        /// </summary>
        public static string Like_NotFound {
            get {
                return ResourceManager.GetString("Like_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastup je uspešno lajkovan..
        /// </summary>
        public static string Like_SuccessAdd {
            get {
                return ResourceManager.GetString("Like_SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lajk je uspešno povučen..
        /// </summary>
        public static string Like_SuccessRemove {
            get {
                return ResourceManager.GetString("Like_SuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis nastupa je obavezan..
        /// </summary>
        public static string Performance_DescriptionRequired {
            get {
                return ResourceManager.GetString("Performance_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muzički žanr je obavezan..
        /// </summary>
        public static string Performance_GenreRequired {
            get {
                return ResourceManager.GetString("Performance_GenreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv nastupa je obavezan..
        /// </summary>
        public static string Performance_NameRequired {
            get {
                return ResourceManager.GetString("Performance_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastup nije pronađen..
        /// </summary>
        public static string Performance_NotFound {
            get {
                return ResourceManager.GetString("Performance_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastup je uspešno obrisan..
        /// </summary>
        public static string Performance_SuccessDelete {
            get {
                return ResourceManager.GetString("Performance_SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biografija je obavezna..
        /// </summary>
        public static string Performer_BiographyRequired {
            get {
                return ResourceManager.GetString("Performer_BiographyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umetničko ime je obavezno..
        /// </summary>
        public static string Performer_StageNameRequired {
            get {
                return ResourceManager.GetString("Performer_StageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme završetka termina je obavezno..
        /// </summary>
        public static string Slot_EndTimeRequired {
            get {
                return ResourceManager.GetString("Slot_EndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme završetka termina mora biti nakon vremena početka!.
        /// </summary>
        public static string Slot_InvalidTimeRange {
            get {
                return ResourceManager.GetString("Slot_InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin nije pronađen..
        /// </summary>
        public static string Slot_NotFound {
            get {
                return ResourceManager.GetString("Slot_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin se mora održati u toku trajanja festivala!.
        /// </summary>
        public static string Slot_OutsideFestivalDates {
            get {
                return ResourceManager.GetString("Slot_OutsideFestivalDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate izabrati binu za ovaj termin..
        /// </summary>
        public static string Slot_StageRequired {
            get {
                return ResourceManager.GetString("Slot_StageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme početka termina je obavezno..
        /// </summary>
        public static string Slot_StartTimeRequired {
            get {
                return ResourceManager.GetString("Slot_StartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin je uspešno obrisan..
        /// </summary>
        public static string Slot_SuccessDelete {
            get {
                return ResourceManager.GetString("Slot_SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip termina je obavezan..
        /// </summary>
        public static string Slot_TypeRequired {
            get {
                return ResourceManager.GetString("Slot_TypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina nije pronađena..
        /// </summary>
        public static string Stage_NotFound {
            get {
                return ResourceManager.GetString("Stage_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneti email nije u ispravnom formatu..
        /// </summary>
        public static string User_EmailInvalid {
            get {
                return ResourceManager.GetString("User_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa je obavezna..
        /// </summary>
        public static string User_EmailRequired {
            get {
                return ResourceManager.GetString("User_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate izabrati omiljeni žanr..
        /// </summary>
        public static string User_FavoriteGenreRequired {
            get {
                return ResourceManager.GetString("User_FavoriteGenreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        public static string User_FirstNameRequired {
            get {
                return ResourceManager.GetString("User_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešan email ili lozinka..
        /// </summary>
        public static string User_InvalidCredentials {
            get {
                return ResourceManager.GetString("User_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        public static string User_LastNameRequired {
            get {
                return ResourceManager.GetString("User_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora imati bar 6 karaktera..
        /// </summary>
        public static string User_PasswordMinLength {
            get {
                return ResourceManager.GetString("User_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna..
        /// </summary>
        public static string User_PasswordRequired {
            get {
                return ResourceManager.GetString("User_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno ste se odjavili..
        /// </summary>
        public static string User_SuccessLogout {
            get {
                return ResourceManager.GetString("User_SuccessLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate biti prijavljeni na sistem da biste izvršili ovu akciju..
        /// </summary>
        public static string User_Unauthorized {
            get {
                return ResourceManager.GetString("User_Unauthorized", resourceCulture);
            }
        }
    }
}
