// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuzickiFestivali.Infrastructure;

#nullable disable

namespace MuzickiFestivali.Infrastructure.Migrations
{
    [DbContext(typeof(MuzickiFestivaliDbContext))]
    [Migration("20260823205320_RenameColumnPotvrdjenDolazak")]
    partial class RenameColumnPotvrdjenDolazak
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Bina", b =>
                {
                    b.Property<int>("idBina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBina"));

                    b.Property<int>("kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("xKoordinata")
                        .HasColumnType("real");

                    b.Property<float>("yKoordinata")
                        .HasColumnType("real");

                    b.HasKey("idBina");

                    b.ToTable("Bine", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Festival", b =>
                {
                    b.Property<int>("idFestival")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFestival"));

                    b.Property<DateTime>("datumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<int>("idOsoba")
                        .HasColumnType("int");

                    b.Property<int>("kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idFestival");

                    b.HasIndex("idOsoba");

                    b.ToTable("Festivali", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Lajkuje", b =>
                {
                    b.Property<int>("idOsoba")
                        .HasColumnType("int");

                    b.Property<int>("idFestival")
                        .HasColumnType("int");

                    b.Property<int>("idNastup")
                        .HasColumnType("int");

                    b.Property<DateTime>("datumVremeLajka")
                        .HasColumnType("datetime2");

                    b.HasKey("idOsoba", "idFestival", "idNastup");

                    b.HasIndex("idFestival", "idNastup");

                    b.ToTable("Lajkovi", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Nastup", b =>
                {
                    b.Property<int>("idFestival")
                        .HasColumnType("int");

                    b.Property<int>("idNastup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idNastup"));

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idFestival", "idNastup");

                    b.ToTable("Nastupi", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Nastupa", b =>
                {
                    b.Property<int>("idOsoba")
                        .HasColumnType("int");

                    b.Property<int>("idFestival")
                        .HasColumnType("int");

                    b.Property<int>("idNastup")
                        .HasColumnType("int");

                    b.Property<int>("idTermin")
                        .HasColumnType("int");

                    b.Property<string>("napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("potvrdjenDolazak")
                        .HasColumnType("bit");

                    b.Property<string>("uloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOsoba", "idFestival", "idNastup", "idTermin");

                    b.HasIndex("idFestival", "idNastup", "idTermin");

                    b.ToTable("Nastupanja", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Osoba", b =>
                {
                    b.Property<int>("idOsoba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOsoba"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOsoba");

                    b.ToTable("Osobe", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Termin", b =>
                {
                    b.Property<int>("idFestival")
                        .HasColumnType("int");

                    b.Property<int>("idNastup")
                        .HasColumnType("int");

                    b.Property<int>("idTermin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTermin"));

                    b.Property<int>("idBina")
                        .HasColumnType("int");

                    b.Property<string>("napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("vremePocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("vremeZavrsetka")
                        .HasColumnType("datetime2");

                    b.HasKey("idFestival", "idNastup", "idTermin");

                    b.HasIndex("idBina");

                    b.ToTable("Termini", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Izvodjac", b =>
                {
                    b.HasBaseType("MuzickiFestivali.Domain.Entities.Osoba");

                    b.Property<string>("biografija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("umetnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Izvodjaci", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Korisnik", b =>
                {
                    b.HasBaseType("MuzickiFestivali.Domain.Entities.Osoba");

                    b.Property<string>("omiljeniZanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Zaposleni", b =>
                {
                    b.HasBaseType("MuzickiFestivali.Domain.Entities.Osoba");

                    b.Property<string>("pozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Zaposleni", (string)null);
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Festival", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Zaposleni", "zaposleni")
                        .WithMany("festivali")
                        .HasForeignKey("idOsoba")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("zaposleni");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Lajkuje", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Korisnik", "korisnik")
                        .WithMany("lajkuje")
                        .HasForeignKey("idOsoba")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MuzickiFestivali.Domain.Entities.Nastup", "nastup")
                        .WithMany("lajkovi")
                        .HasForeignKey("idFestival", "idNastup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("korisnik");

                    b.Navigation("nastup");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Nastup", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Festival", "festival")
                        .WithMany("nastupi")
                        .HasForeignKey("idFestival")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("festival");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Nastupa", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Izvodjac", "izvodjac")
                        .WithMany("nastupa")
                        .HasForeignKey("idOsoba")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MuzickiFestivali.Domain.Entities.Termin", "termin")
                        .WithMany("izvodjaci")
                        .HasForeignKey("idFestival", "idNastup", "idTermin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("izvodjac");

                    b.Navigation("termin");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Termin", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Bina", "bina")
                        .WithMany("termini")
                        .HasForeignKey("idBina")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MuzickiFestivali.Domain.Entities.Nastup", "nastup")
                        .WithMany("termini")
                        .HasForeignKey("idFestival", "idNastup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bina");

                    b.Navigation("nastup");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Izvodjac", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Osoba", null)
                        .WithOne()
                        .HasForeignKey("MuzickiFestivali.Domain.Entities.Izvodjac", "idOsoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Korisnik", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Osoba", null)
                        .WithOne()
                        .HasForeignKey("MuzickiFestivali.Domain.Entities.Korisnik", "idOsoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Zaposleni", b =>
                {
                    b.HasOne("MuzickiFestivali.Domain.Entities.Osoba", null)
                        .WithOne()
                        .HasForeignKey("MuzickiFestivali.Domain.Entities.Zaposleni", "idOsoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Bina", b =>
                {
                    b.Navigation("termini");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Festival", b =>
                {
                    b.Navigation("nastupi");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Nastup", b =>
                {
                    b.Navigation("lajkovi");

                    b.Navigation("termini");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Termin", b =>
                {
                    b.Navigation("izvodjaci");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Izvodjac", b =>
                {
                    b.Navigation("nastupa");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Korisnik", b =>
                {
                    b.Navigation("lajkuje");
                });

            modelBuilder.Entity("MuzickiFestivali.Domain.Entities.Zaposleni", b =>
                {
                    b.Navigation("festivali");
                });
#pragma warning restore 612, 618
        }
    }
}
